table dim_especialidade
	lineageTag: d5f091e9-e606-4177-8677-e84f97d4b7d5

	column id_especialidade
		dataType: int64
		formatString: 0
		lineageTag: 7c413bff-a13f-45c8-a3d1-27ff55c9f91f
		summarizeBy: none
		sourceColumn: id_especialidade

		annotation SummarizationSetBy = Automatic

	column especialidade
		dataType: string
		lineageTag: 3d21e87b-654f-4ac7-9991-4bae72652854
		summarizeBy: none
		sourceColumn: especialidade

		annotation SummarizationSetBy = Automatic

	partition dim_especialidade = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\Documents\Processo Seletivo\Teste\dados\tratados\dim_especialidade.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id_especialidade", Int64.Type}, {"especialidade", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

